# Generated by Django 4.0.6 on 2022-10-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_timestamp_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
    ]
